version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: decks-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=decks
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: decks-pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@localhost
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - '8050:80'
    depends_on:
      - postgres

  redis:
    image: redis
    container_name: decks-redis
    restart: unless-stopped
    command: redis-server --requirepass Oj3-ks96D91Yx
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  redsight:
    image: redislabs/redisinsight:latest
    container_name: decks-redsight
    restart: unless-stopped
    volumes:
      - redsight_data:/db
    ports:
      - '8001:8001'
    depends_on:
      - redis

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:
  redsight_data:
