version: '3.7'

services:
  postgres:
    image: postgres
    container_name: decks_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    # build: ./libs/database/pgadmin
    image: dpage/pgadmin4
    container_name: decks_pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - '8050:80'
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
